In [1]:
import numpy as np

In [2]:
print (np.__version__)

1.20.1


In [4]:
my_array = np.array(np.arange(10))
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
my_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [7]:
my_array*3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [8]:
my_matrix = np.asmatrix(np.array(np.arange(9)).reshape((3,3)))

In [9]:
my_matrix

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [10]:
my_matrix.T

matrix([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])